In [4]:
import numpy as np
import pandas as pd
# from alinea.caribu.CaribuScene import CaribuScene

# from openalea.archicrop.display import build_scene
# from openalea.archicrop.stand import compute_domain
# from openalea.archicrop.stics_io import stics_weather_3d
# from openalea.archicrop.sky_sources import meteo_day
from openalea.astk.sky_irradiance import sky_irradiance
from openalea.astk.sky_sources import caribu_light_sources, sky_sources

In [5]:
weather_file = '../data/ntarla_corr.2018'
location = {  
'longitude': 3.87,
'latitude': 12.58,
'altitude': 800,
'timezone': 'Europe/Paris'}

def meteo_day(filename):
    names=['station', 'year', 'month', 'day', 'julian', 'min_temp', 'max_temp', 'rad', 'Penman PET', 'rainfall', 'wind', 'pressure', 'CO2']
    df = pd.read_csv(filename,  header=None, sep='\s+', names=names)  # noqa: PD901
    df["daydate"] = pd.to_datetime(df[["year", "month", "day"]])
    return df

df = meteo_day(weather_file) 

# irr = sky_irradiance(daydate=par.daydate, day_ghi=par.rad, **location)
# sun, sky = sky_sources(sky_type='clear_sky', sky_irradiance=irr, scale='global')

<>:10: SyntaxWarning: invalid escape sequence '\s'
<>:10: SyntaxWarning: invalid escape sequence '\s'
C:\Users\cheriere\AppData\Local\Temp\ipykernel_7976\3442412617.py:10: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(filename,  header=None, sep='\s+', names=names)  # noqa: PD901

In [6]:
df

,station,year,month,day,julian,min_temp,max_temp,rad,Penman PET,rainfall,wind,pressure,CO2,daydate
0,ntarla,2018,1,1,1,5.5,32.7,16.2,-999.9,0.0,3.0,9.1,408.72,2018-01-01
1,ntarla,2018,1,2,2,8.4,33.5,15.5,-999.9,0.0,2.8,10.2,408.72,2018-01-02
2,ntarla,2018,1,3,3,6.5,33.5,14.4,-999.9,0.0,2.5,10.7,408.72,2018-01-03
3,ntarla,2018,1,4,4,7.4,33.5,15.4,-999.9,0.0,2.4,12.3,408.72,2018-01-04
4,ntarla,2018,1,5,5,8.0,34.6,17.4,-999.9,0.0,2.4,10.6,408.72,2018-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,ntarla,2018,12,27,361,12.0,34.0,16.4,-999.9,0.0,2.0,16.6,408.72,2018-12-27
361,ntarla,2018,12,28,362,13.5,35.5,16.4,-999.9,0.0,1.5,17.2,408.72,2018-12-28
362,ntarla,2018,12,29,363,15.3,36.0,15.2,-999.9,0.0,1.1,20.1,408.72,2018-12-29
363,ntarla,2018,12,30,364,16.5,36.0,14.9,-999.9,0.0,2.0,19.8,408.72,2018-12-30
364,ntarla,2018,12,31,365,16.5,35.5,15.2,-999.9,0.0,2.6,16.5,408.72,2018-12-31

In [7]:
irr = sky_irradiance(daydate='2018-01-01', day_ghi=16.2, **location)
irr

,azimuth,zenith,elevation,ghi,dni,dhi,ppfd
2018-01-01 08:00:00+01:00,116.852907,78.824133,11.175867,75.086788,21.830070,70.855659,181.099773
2018-01-01 09:00:00+01:00,122.424026,66.124478,23.875522,266.411079,203.698868,183.963767,583.672871
2018-01-01 10:00:00+01:00,130.713674,54.349069,35.650931,447.320081,346.920202,245.119197,943.631464
2018-01-01 11:00:00+01:00,143.241897,44.307239,45.692761,586.167826,373.177537,319.120307,1213.972079
2018-01-01 12:00:00+01:00,161.630074,37.447399,52.552601,668.945821,418.848477,336.417037,1373.716033
2018-01-01 13:00:00+01:00,184.705383,35.667900,54.332100,688.570720,421.336322,346.272739,1411.475015
2018-01-01 14:00:00+01:00,206.425477,39.661050,50.338950,643.438983,415.229734,323.781175,1324.580302
2018-01-01 15:00:00+01:00,222.377510,48.003206,41.996794,537.269488,372.817488,287.821397,1119.166653
2018-01-01 16:00:00+01:00,233.010589,58.864037,31.135963,379.551073,308.044023,220.270538,810.109475
2018-01-01 17:00:00+01:00,240.080163,71.079440,18.920560,188.623469,162.186538,136.033365,424.186672
2018-01-01 18:00:00+01:00,244.860645,83.986057,6.013943,18.614672,0.000000,18.614672,49.690812

In [8]:
sum(irr.ghi * 3600)*1e-6

16.200000000000003

In [9]:
(irr.ghi - irr.dhi)/ irr.ghi

2018-01-01 08:00:00+01:00    0.056350
2018-01-01 09:00:00+01:00    0.309474
2018-01-01 10:00:00+01:00    0.452027
2018-01-01 11:00:00+01:00    0.455582
2018-01-01 12:00:00+01:00    0.497094
2018-01-01 13:00:00+01:00    0.497114
2018-01-01 14:00:00+01:00    0.496796
2018-01-01 15:00:00+01:00    0.464289
2018-01-01 16:00:00+01:00    0.419655
2018-01-01 17:00:00+01:00    0.278810
2018-01-01 18:00:00+01:00    0.000000
Freq: h, dtype: float64

In [10]:
sun, sky = sky_sources(sky_type='clear_sky', sky_irradiance=irr, scale='global', source_irradiance='horizontal')

In [11]:
sun

[]

In [12]:
sky

[(90.0, 270.0, 0.39100667183394583),
 (26.57, 90.0, 0.1684830635755709),
 (26.57, 18.0, 0.22501472975731676),
 (26.57, 306.0, 0.4997597140809673),
 (26.57, 234.0, 0.492511328108903),
 (26.57, 162.0, 0.22317789601517124),
 (52.62, 54.0, 0.26938274628806247),
 (52.62, 342.0, 0.5631236057886033),
 (52.62, 270.0, 0.942723570389056),
 (52.62, 198.0, 0.5569442992225825),
 (52.62, 126.0, 0.2687336637263559),
 (10.81, 54.0, 0.13940571598413445),
 (10.81, 342.0, 0.2554477190930356),
 (10.81, 270.0, 0.2467171050695601),
 (10.81, 198.0, 0.24794322104920383),
 (10.81, 126.0, 0.1396195728434529),
 (69.16, 90.0, 0.2986082051994004),
 (69.16, 18.0, 0.38744229379548595),
 (69.16, 306.0, 0.6757002934820833),
 (69.16, 234.0, 0.6723467544052899),
 (69.16, 162.0, 0.3855602884568046),
 (47.41, 90.0, 0.22176052981476205),
 (47.41, 18.0, 0.3163797789476275),
 (47.41, 306.0, 0.826047482694181),
 (47.41, 234.0, 0.8182564587799547),
 (47.41, 162.0, 0.31396103814112897),
 (31.08, 66.73000000000002, 0.20799573979564412),
 (31.08, 41.26999999999998, 0.22932988384293204),
 (31.08, 354.73, 0.3883838382452843),
 (31.08, 329.27, 0.6192861367422303),
 (31.08, 282.73, 0.6011551460397923),
 (31.08, 257.27, 0.5978952120090412),
 (31.08, 210.73000000000002, 0.6070822649370445),
 (31.08, 185.26999999999998, 0.3820564513032689),
 (31.08, 138.73000000000002, 0.2287989794784403),
 (31.08, 113.26999999999998, 0.20803179083268003),
 (9.23, 77.76999999999998, 0.10713181791446759),
 (9.23, 30.230000000000018, 0.11863271263701766),
 (9.23, 5.769999999999982, 0.14399548478975815),
 (9.23, 318.23, 0.22561346000224464),
 (9.23, 293.77, 0.20134212639136317),
 (9.23, 246.23000000000002, 0.199255858095406),
 (9.23, 221.76999999999998, 0.2202283400757125),
 (9.23, 174.23000000000002, 0.14210725060733012),
 (9.23, 149.76999999999998, 0.11837013807871298),
 (9.23, 102.23000000000002, 0.1072496216389929)]

In [13]:
len(sky)

46

In [14]:
sum([s[2] for s in sky])

16.200000000000003